repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
        exclude: .specs|.bzl|.patch
      - id: trailing-whitespace
        exclude: .specs|.bzl|.patch|BUILD|.bazelrc
      - id: mixed-line-ending
        exclude: .specs|.bzl|.patch
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--target-version, py38]
