VCAST_PKG = "//devops/cicd/scripts/python/vcast"

py_test(
    name = "test_vcast_utils",
    srcs = ["test_vcast_utils.py"],
    deps = [
        VCAST_PKG,
    ],
)

py_test(
    name = "test_convert_bazel_actions",
    srcs = ["test_convert_bazel_actions.py"],
    deps = [
        VCAST_PKG,
    ],
)

py_test(
    name = "test_merge_coverage_results",
    srcs = ["test_merge_coverage_results.py"],
    deps = [
        VCAST_PKG,
    ],
)
