package(default_visibility = ["//visibility:public"])

filegroup(
    name = "Gen20x_Civic_i3_ECU_Extract",
    srcs = [
        "Gen20x_Civic_i3_ECU_Extract.arxml",
    ],
)

filegroup(
    name = "x6aa_idc_ecu_extract_arxml",
    srcs = [
        "X6AA_IDC_M_P_STAR_35_Ecu_Extract_2021_17a0_AR44.arxml",
    ],
)
