package(default_visibility = ["//visibility:public"])

py_library(
    name = "vcast",
    srcs = [
        "convert_bazel_actions.py",
        "merge_coverage_results.py",
        "utils.py",
    ],
)
