package(default_visibility = ["//visibility:public"])

filegroup(
    name = "logging_config",
    srcs = [
        "config/logging_config.json",
    ],
)

filegroup(
    name = "exec_config",
    srcs = [
        "config/exec_config.json",
    ],
)

filegroup(
    name = "someip_config",
    srcs = [
        "config/someipd-posix.json",
    ],
)
