package(default_visibility = ["//visibility:public"])

filegroup(
    name = "someip_posix_json",
    srcs = ["someipd_posix/someipd-posix.json"],
)

filegroup(
    name = "logging_config_json",
    srcs = ["sw_update_client_minerva_adapter/logging_config.json"],
)

filegroup(
    name = "com_application_json",
    srcs = ["sw_update_client_minerva_adapter/com_application.json"],
)